version: "3.7"
services:
  nginx-proxy:
    hostname: nginx-proxy
    build: ./nginx-proxy
    image: nginx-proxy
    deploy:
      replicas: 1
    ports:
      - "1234:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      retries: 4
      start_period: 10s

  backend:
    hostname: backend
    build: ./backend
    image: nginx-backend
    deploy:
      replicas: 1
    ports:
      - "1235:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      retries: 4
      start_period: 10s

networks:
  default:
    name: plump-net
    external: true